default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Play Store Internal Test Track"
  lane :beta do
    gradle(task: "bundleRelease")
    upload_to_play_store(track: 'internal')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "bundleRelease")
    upload_to_play_store(track: 'production')
  end
end
